### PR TITLE
Add an option to hide the power save warning at startup

### PR DESCRIPTION
**Pull request by mags0ft**
Hello again @Jeffser, here is the pull request without translation files.

I added an option mostly for laptop users to allow omitting the power saver warning at startup because it might get annoying for some people.

For context, many users are regularly using power saver for long periods of time to get longer battery life on mobile devices. This patch gives them the option to not get warned about the very thing they're aware of everytime they use Alpaca:

image

Hope I could help!

### CODE REVIEW

**Comment by Jeffser** [comment]
I'll change it to be a positive switch

Hide power saver warning -> show power saver warning

**Comment by mags0ft** [comment]
Okay, also good! The banner should then still be shown by default, though, as some users on desktop also use power save and might wonder about decreased performance! 👍

**Comment by Jeffser** [comment]
Alright I changed it to a positive switch and fixed some small problems, everything is tested and working, thanks for your contribution!

**Comment by mags0ft** [comment]
Amazing! Happy I could contribute a little. ☺️

**Pull request merged**
