### PR TITLE
Code block and chat improvements

### PR DESCRIPTION
**Pull request by Nokse22**
Screenshot from 2024-05-25 21-45-54

## Works also in dark mode

Screenshot from 2024-05-25 21-45-38

### Other things
- added margin to the user message to distinguish it more easily
- moved toast overlay so it doesn't interfere with the message box
- toast when code is copied

### CODE REVIEW

**Comment by Nokse22** [comment]
Also, I would highly suggest you to try to use custom widgets to organize and divide your code, so it won't become just a giant `window.py` file.

**Comment by Jeffser** [comment]
Hi thanks for the work, it looks great, I'm not sure how custom widgets work, what I wanted to do before the 1.0.0 release was divide all the window.py code between multiple python files. Today I'm taking a break but I might do that tomorrow

**Comment by Nokse22** [comment]
Glad you like it.
Dividing the code is good too.

Another thing that you can do if you want is to move the UI files, icons and css to the data folder (changing some meson file).

Custom widgets can be very useful because you can define the layout with a UI file inheriting from GTK or Adw widgets, and have all the code related to that in a separate file. You can also define signals and connect to them.

**Comment by Jeffser** [comment]
for now I'm going to separate some code into different py files

**Comment by Jeffser** [comment]
https://github.com/Jeffser/Alpaca/commit/1cf2f04b0676ce63dee1bb8c4608ce89e64b0597

I just separated some stuff, I'm still working on making the code more readable

**Pull request merged**
