### PR TITLE
add an option to hide the power save warning at startup

### PR DESCRIPTION
**Pull request by mags0ft**
Hello @Jeffser, and thanks for this amazing project! I really like it.

I added an option for mostly laptop users to omit the power saver warning at startup because it might get annoying for some people.

Many users are regularly using power saver for long periods of time to get longer battery life on mobile devices. This patch gives them the option to not get warned about the very thing they're aware of everytime they use Alpaca:

image

I also already updated the translation files and added a German translation.

Hope I could help, let me know what you think! :)

### CODE REVIEW

**Comment by Jeffser** [comment]
Hi, thanks for your help, could you remove the translations files from the pr? I'll update them after

**Comment by Jeffser** [comment]
I shouldn't have deleted that file, my bad

**Comment by Jeffser** [comment]
Just please make another pr without the languages stuff

**Comment by mags0ft** [comment]
Okay, no problem. Wait a sec

**Comment by mags0ft** [comment]
New pull request is #282! :)

**Pull request closed without merging**
