### PR TITLE
Improved chat view and message bar

### PR DESCRIPTION
**Pull request by Nokse22**
Screenshot from 2024-05-23 23-26-15
Screenshot from 2024-05-23 23-26-12

Hope you like it, I have kept the message view sensitive even when a the AI is responding, because it can be useful to write while it's responding.

I have also added clamps for the message bar and chat view.

Plus some minor fixes.

### CODE REVIEW

**Comment by Jeffser** [comment]
Hi thanks for the help, I'm in class right now, I will check it out in a couple of hours, I see you made new CSS files, I may need to change that because a CSS caused some errors with some users for some reason.

**Comment by Jeffser** [comment]
Btw I'm surprised you understood my spaghetti code hahaha

**Comment by Nokse22** [comment]
Hi, no problem, check it when you want, now stop getting distracted and get back to class! 😉

**Comment by Jeffser** [comment]
yessir hahahaha

**Comment by Jeffser** [comment]
Looks good, thanks for the contribution, do you want to be in the 'thank you' section of the readme?

**Comment by Nokse22** [comment]
Ok, thank you!

**Pull request merged**
